spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql?serverTimezone=Asia/Seoul
    username: song2
    password: noonsong123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true # JPA의 구현체인 Hibernate가 동작하면서 발생한 SQL의 가독성을 높여준다.
        show_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 439336342405-kjsaaodjc5coet1chmjg3fmq948vg7mi.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/auth/google/callback
            authorization-grant-type: code

          naver:
            client-id: oeiI6UyzGUxfwwnLq7_l
            client-secret: GZpMu07z7f
            #yaml 에서는 / (슬러시)를 그대로 쓰면 파싱 에러가 난다. 따옴표나 작은 따옴표로 감싸주어야함
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            # = http://localhost:8080/login/oauth2/code/naver
            scope: name,email,mobile
            client-name: Naver
            authorization-grant-type: authorization_code


        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            # 기준이 되는 user_name 의 이름을 네이버에서는 response로 지정해야한다. (네이버 회원 조회시 반환되는 JSON 형태 떄문이다)
            user_name_attribute: response


logging:
  level:
    com.tutorial: debug
    org.apache.http: debug
    httpclient.wire: debug

jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK

