spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql?serverTimezone=Asia/Seoul
    username: song2
    password: noonsong123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true # JPA의 구현체인 Hibernate가 동작하면서 발생한 SQL의 가독성을 높여준다.
        show_sql: true

  security:
    oauth2:
      client:
         registration:
           google:
             url: https://accounts.google.com/o/oauth2/v2/auth
             client-id: 439336342405-um4lraa4ija50rvj6hne50b247c90r36.apps.googleusercontent.com
             client-secret: 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
             callback:
               url: http://localhost:8080/auth/google/callback
             response_type: code
             scope:
               - email
               - profile

logging:
  level:
    com.tutorial: debug

jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK

